name: tester
on: push
jobs:
  build-lin:
    name: Test the tester itself
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v1
      - name: Run build on Linux
        run: make
